using Cms.Repository.Enums;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Cms.Repository.Configurations.Seeds;

public static class ServiceSeed
{
    public static void SeedService(this EntityTypeBuilder<Entities.Service> builder)
    {
        builder.HasData(
            new Entities.Service
            {
                Id = SeedIds.ServiceMain,
                Title = "Perlunas Signature Tour",
                Slug = "perlunas-signature-tour",
                BestSeller = true,
                Introducetion = "Sample introduction for the main service.",
                Day = 3,
                Night = 2,
                Label = "Featured",
                Album = "[]",
                Region = "Vietnam",
                Description = "Sample service description.",
                Infor = "Sample service information.",
                Highlight = new List<string> { "Sample service highlights." },
                Code = "PLN-001",
                Instruct = "Sample instructions.",
                Feature = "Sample features.",
                Type = ServiceType.Tour,
                IsPublic = true,
                CreatedAt = SeedIds.CreatedAt,
                UpdatedAt = SeedIds.CreatedAt,
            },
            new Entities.Service
            {
                Id = SeedIds.ServiceResort,
                Title = "Beach Resort Package",
                Slug = "beach-resort-package",
                BestSeller = false,
                Day = 4,
                Night = 3,
                Album = "[]",
                Region = "Da Nang",
                Description = "Beachfront resort package.",
                Infor = "Includes room and breakfast.",
                Highlight = new List<string> { "Private beach", "spa", "local dining" },
                Code = "PLN-002",
                Type = ServiceType.Hotel,
                IsPublic = true,
                PurposeOfTrip = PurposeOfTrip.ResortVacation,
                Destination = "Da Nang Beach",
                Form = "Full-board",
                CreatedAt = SeedIds.CreatedAt,
                UpdatedAt = SeedIds.CreatedAt,
            },
            new Entities.Service
            {
                Id = SeedIds.ServicePrivate,
                Title = "Private Custom Journey",
                Slug = "private-custom-journey",
                BestSeller = false,
                Introducetion = "Custom private trip with flexible schedule.",
                Day = 2,
                Night = 1,
                Label = "Private",
                Album = "[]",
                Region = "Hoi An",
                Description = "Private travel experience.",
                Infor = "Dedicated guide and vehicle.",
                Highlight = new List<string> { "Flexible route", "private guide" },
                Code = "PLN-003",
                Instruct = "Confirm itinerary before departure.",
                Feature = "Private guide, custom route",
                Type = ServiceType.Combo,
                IsPublic = true,
                PurposeOfTrip = PurposeOfTrip.Sightseeing,
                Destination = "Hoi An Ancient Town",
                Form = "Half-board",
                Classify = Classify.Akoya,
                CreatedAt = SeedIds.CreatedAt,
                UpdatedAt = SeedIds.CreatedAt,
            },
            new Entities.Service
            {
                Id = Guid.Parse("11111111-1111-1111-1111-222222222211"),
                Title = "Vietnam Eco Lodge",
                Slug = "vietnam-eco-lodge",
                BestSeller = false,
                Introducetion = "Scenic lodge in the heart of nature.",
                Album = "[]",
                Region = "Vietnam",
                Instruct = "Eco guidelines apply.",
                Feature = "Mountain view, organic restaurant",
                Type = ServiceType.Hotel,
                IsPublic = true,
                PurposeOfTrip = PurposeOfTrip.ResortVacation,
                Destination = "Sapa Valley",
                Form = "Bed and breakfast",
                CreatedAt = SeedIds.CreatedAt,
                UpdatedAt = SeedIds.CreatedAt,
            },
            new Entities.Service
            {
                Id = Guid.Parse("11111111-1111-1111-1111-222222222212"),
                Title = "Hanoi Royal Palace Hotel",
                Slug = "hanoi-royal-palace-hotel",
                BestSeller = true,
                Introducetion = "Luxury hotel in the historical quarter.",
                Album = "[]",
                Region = "Vietnam",
                Instruct = "Check-in after 14:00.",
                Feature = "City view, spa, fitness center",
                Type = ServiceType.Hotel,
                IsPublic = true,
                PurposeOfTrip = PurposeOfTrip.Sightseeing,
                Destination = "Hanoi Old Quarter",
                Form = "Room only",
                CreatedAt = SeedIds.CreatedAt,
                UpdatedAt = SeedIds.CreatedAt,
            },
            new Entities.Service
            {
                Id = Guid.Parse("11111111-1111-1111-1111-222222222213"),
                Title = "Saigon Heritage Hotel",
                Slug = "saigon-heritage-hotel",
                BestSeller = false,
                Introducetion = "Elegant boutique hotel reflecting local heritage.",
                Album = "[]",
                Region = "Vietnam",
                Instruct = "Strictly non-smoking.",
                Feature = "Rooftop bar, pool",
                Type = ServiceType.Hotel,
                IsPublic = true,
                PurposeOfTrip = PurposeOfTrip.Sightseeing,
                Destination = "Ho Chi Minh City",
                Form = "Room only",
                CreatedAt = SeedIds.CreatedAt,
                UpdatedAt = SeedIds.CreatedAt,
            },
            new Entities.Service
            {
                Id = Guid.Parse("11111111-1111-1111-1111-222222222214"),
                Title = "Phu Quoc Sunset Resort",
                Slug = "phu-quoc-sunset-resort",
                BestSeller = false,
                Introducetion = "Seaside resort with stunning sunset views.",
                Album = "[]",
                Region = "Vietnam",
                Instruct = "No pets allowed.",
                Feature = "Private beach, infinity pool",
                Type = ServiceType.Hotel,
                IsPublic = true,
                PurposeOfTrip = PurposeOfTrip.ResortVacation,
                Destination = "Phu Quoc Island",
                Form = "Full-board",
                CreatedAt = SeedIds.CreatedAt,
                UpdatedAt = SeedIds.CreatedAt,
            },
            new Entities.Service
            {
                Id = Guid.Parse("11111111-1111-1111-1111-333333333311"),
                Title = "Vietnam Heritage Discovery Tour",
                Slug = "vietnam-heritage-discovery-tour",
                BestSeller = false,
                Introducetion = "Sample tour in Vietnam.",
                Day = 5,
                Night = 4,
                Album = "[]",
                Region = "Vietnam",
                Description = "Explore rich heritage.",
                Infor = "All inclusive tour.",
                Highlight = new List<string> { "Historic sites." },
                Code = "TOUR-VN1",
                Type = ServiceType.Tour,
                IsPublic = true,
                CreatedAt = SeedIds.CreatedAt,
                UpdatedAt = SeedIds.CreatedAt,
            },
            new Entities.Service
            {
                Id = Guid.Parse("11111111-1111-1111-1111-333333333312"),
                Title = "Vietnam Northern Highlights",
                Slug = "vietnam-northern-highlights",
                BestSeller = false,
                Introducetion = "Sample tour in northern Vietnam.",
                Day = 6,
                Night = 5,
                Album = "[]",
                Region = "Vietnam",
                Description = "Explore natural highlights.",
                Infor = "All inclusive tour.",
                Highlight = new List<string> { "Spectacular bays." },
                Code = "TOUR-VN2",
                Type = ServiceType.Tour,
                IsPublic = true,
                CreatedAt = SeedIds.CreatedAt.AddHours(1),
                UpdatedAt = SeedIds.CreatedAt.AddHours(1),
            },
            new Entities.Service
            {
                Id = Guid.Parse("11111111-1111-1111-1111-333333333313"),
                Title = "Thailand Paradise Getaway",
                Slug = "thailand-paradise-getaway",
                BestSeller = false,
                Introducetion = "Sample tour in Thailand.",
                Day = 4,
                Night = 3,
                Album = "[]",
                Region = "Thailand",
                Description = "Explore Thai islands.",
                Infor = "Flight not included.",
                Highlight = new List<string> { "Bangkok and Phuket." },
                Code = "TOUR-TH1",
                Type = ServiceType.Tour,
                IsPublic = true,
                CreatedAt = SeedIds.CreatedAt,
                UpdatedAt = SeedIds.CreatedAt,
            });
    }
}
