// <auto-generated />
using System;
using Cms.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cms.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260702040036_UpdateRoomCategoryAndSchedule")]
    partial class UpdateRoomCategoryAndSchedule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cms.Repository.Entities.Blog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ReadingTime")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SubTitile")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Tag")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Titile")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Blogs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888881"),
                            Author = "Perlunas Admin",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sample blog content.",
                            IsDeleted = false,
                            ReadingTime = "5 min",
                            SubTitile = "Start here",
                            Tag = "guide",
                            Titile = "Sample travel guide",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888882"),
                            Author = "Perlunas Admin",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tips for selecting a resort package.",
                            IsDeleted = false,
                            ReadingTime = "7 min",
                            SubTitile = "Family travel tips",
                            Tag = "resort",
                            Titile = "How to choose a resort",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888883"),
                            Author = "Perlunas Admin",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "How to prepare for a private custom trip.",
                            IsDeleted = false,
                            ReadingTime = "6 min",
                            SubTitile = "Flexible journeys",
                            Tag = "private-tour",
                            Titile = "Private tour planning",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Cms.Repository.Entities.DepartureSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccommodationStandards")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Price")
                        .HasColumnType("text");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("StartTime")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("DepartureSchedules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444441"),
                            AccommodationStandards = "3-star hotel",
                            Code = "DEP-001",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Price = "3500000/customer",
                            ServiceId = new Guid("11111111-1111-1111-1111-111111111111"),
                            StartTime = "2026-07-15",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444442"),
                            AccommodationStandards = "4-star resort",
                            Code = "DEP-002",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Price = "5200000/customer",
                            ServiceId = new Guid("11111111-1111-1111-1111-111111111111"),
                            StartTime = "2026-09-20",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444443"),
                            AccommodationStandards = "Boutique hotel",
                            Code = "DEP-003",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Price = "Quote on request",
                            ServiceId = new Guid("11111111-1111-1111-1111-111111111111"),
                            StartTime = "On request",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Cms.Repository.Entities.ImportantInfor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubTitle")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("ImportantInfors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555551"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cancellation terms depend on departure date.",
                            IsDeleted = false,
                            ServiceId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SubTitle = "Important before booking",
                            Title = "Cancellation policy",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555552"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Guests must present valid identification at check-in.",
                            IsDeleted = false,
                            ServiceId = new Guid("11111111-1111-1111-1111-111111111113"),
                            SubTitle = "Required documents",
                            Title = "Resort check-in",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555553"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Final itinerary must be confirmed 48 hours before departure.",
                            IsDeleted = false,
                            ServiceId = new Guid("11111111-1111-1111-1111-111111111113"),
                            SubTitle = "Custom planning",
                            Title = "Private itinerary",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Cms.Repository.Entities.PageContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentValue")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Kind")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Label")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PageKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("SectionKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("SoftOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("PageKey", "SectionKey", "Key");

                    b.ToTable("PageContents", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666661"),
                            ContentValue = "Discover Perlunas",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Key = "title",
                            Kind = "text",
                            Label = "Hero title",
                            PageKey = "home",
                            SectionKey = "hero",
                            SoftOrder = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666662"),
                            ContentValue = "We craft thoughtful travel experiences.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Key = "description",
                            Kind = "textarea",
                            Label = "About intro",
                            PageKey = "about",
                            SectionKey = "intro",
                            SoftOrder = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666663"),
                            ContentValue = "Choose a journey that fits your style.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Key = "subtitle",
                            Kind = "text",
                            Label = "Service banner subtitle",
                            PageKey = "services",
                            SectionKey = "banner",
                            SoftOrder = 2,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666671"),
                            ContentValue = "Explore breathtaking destinations with us",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Key = "subtitle",
                            Kind = "text",
                            Label = "Hero subtitle",
                            PageKey = "home",
                            ParentId = new Guid("66666666-6666-6666-6666-666666666661"),
                            SectionKey = "hero",
                            SoftOrder = 2,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666672"),
                            ContentValue = "Book Now",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Key = "cta",
                            Kind = "text",
                            Label = "Hero CTA button",
                            PageKey = "home",
                            ParentId = new Guid("66666666-6666-6666-6666-666666666661"),
                            SectionKey = "hero",
                            SoftOrder = 3,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Cms.Repository.Entities.RoomCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Acreage")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Album")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Feature")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("NumberOfBed")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("NumberOfCustomer")
                        .HasColumnType("integer");

                    b.Property<string>("OriginalPrice")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Price")
                        .HasColumnType("text");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Titile")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Unit")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("RoomCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333331"),
                            Acreage = "35m2",
                            Album = "[]",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sample deluxe room.",
                            Feature = "Balcony, breakfast, sea view",
                            IsDeleted = false,
                            NumberOfBed = "1",
                            NumberOfCustomer = 2,
                            OriginalPrice = "1500000",
                            Price = "1200000",
                            ServiceId = new Guid("11111111-1111-1111-1111-111111111112"),
                            Titile = "Deluxe Room",
                            Unit = "đêm",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333332"),
                            Acreage = "80m2",
                            Album = "[]",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Private family villa near the beach.",
                            Feature = "Private pool, kitchen, breakfast",
                            IsDeleted = false,
                            NumberOfBed = "2",
                            NumberOfCustomer = 4,
                            OriginalPrice = "4000000",
                            Price = "3500000",
                            ServiceId = new Guid("11111111-1111-1111-1111-111111111112"),
                            Titile = "Family Villa",
                            Unit = "đêm",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Acreage = "45m2",
                            Album = "[]",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Suite for private journey guests.",
                            Feature = "Old town view, breakfast",
                            IsDeleted = false,
                            NumberOfBed = "1",
                            NumberOfCustomer = 2,
                            OriginalPrice = "2200000",
                            ServiceId = new Guid("11111111-1111-1111-1111-111111111113"),
                            Titile = "Heritage Suite",
                            Unit = "đêm",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Cms.Repository.Entities.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Day")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sumary")
                        .HasColumnType("text");

                    b.Property<string>("Titile")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("Schedules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222221"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Day = "Day 1",
                            Description = "Airport pickup and welcome dinner.",
                            IsDeleted = false,
                            ServiceId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Sumary = "Arrive and settle in.",
                            Titile = "Arrival",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Day = "Day 2",
                            Description = "Guided tour and local activities.",
                            IsDeleted = false,
                            ServiceId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Sumary = "Explore the destination.",
                            Titile = "Experience",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222223"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Day = "Day 1",
                            Description = "Welcome drink, room check-in, free beach time.",
                            IsDeleted = false,
                            ServiceId = new Guid("11111111-1111-1111-1111-111111111112"),
                            Sumary = "Check in and relax.",
                            Titile = "Resort check-in",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222224"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Day = "Day 1",
                            Description = "Custom stops based on customer preference.",
                            IsDeleted = false,
                            ServiceId = new Guid("11111111-1111-1111-1111-111111111113"),
                            Sumary = "Private tour with local guide.",
                            Titile = "Private discovery",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Cms.Repository.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Album")
                        .HasColumnType("text");

                    b.Property<string>("Classify")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("Day")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Destination")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Feature")
                        .HasColumnType("text");

                    b.Property<string>("Form")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Highlight")
                        .HasColumnType("text");

                    b.Property<string>("Infor")
                        .HasColumnType("text");

                    b.Property<string>("Instruct")
                        .HasColumnType("text");

                    b.Property<string>("Introducetion")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("Night")
                        .HasColumnType("integer");

                    b.Property<string>("PurposeOfTrip")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Region")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("Type");

                    b.ToTable("Services", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Album = "[]",
                            Code = "PLN-001",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Day = 3,
                            Description = "Sample service description.",
                            Feature = "Sample features.",
                            Highlight = "Sample service highlights.",
                            Infor = "Sample service information.",
                            Instruct = "Sample instructions.",
                            Introducetion = "Sample introduction for the main service.",
                            IsDeleted = false,
                            IsPublic = true,
                            Label = "Featured",
                            Night = 2,
                            Region = "Vietnam",
                            Title = "Perlunas Signature Tour",
                            Type = "Tour",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            Album = "[]",
                            Code = "PLN-002",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Day = 4,
                            Description = "Beachfront resort package.",
                            Destination = "Da Nang Beach",
                            Form = "Full-board",
                            Highlight = "Private beach, spa, local dining",
                            Infor = "Includes room and breakfast.",
                            IsDeleted = false,
                            IsPublic = true,
                            Night = 3,
                            PurposeOfTrip = "ResortVacation",
                            Region = "Da Nang",
                            Title = "Beach Resort Package",
                            Type = "Hotel",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111113"),
                            Album = "[]",
                            Classify = "Akoya",
                            Code = "PLN-003",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Day = 2,
                            Description = "Private travel experience.",
                            Destination = "Hoi An Ancient Town",
                            Feature = "Private guide, custom route",
                            Form = "Half-board",
                            Highlight = "Flexible route, private guide",
                            Infor = "Dedicated guide and vehicle.",
                            Instruct = "Confirm itinerary before departure.",
                            Introducetion = "Custom private trip with flexible schedule.",
                            IsDeleted = false,
                            IsPublic = true,
                            Label = "Private",
                            Night = 1,
                            PurposeOfTrip = "Sightseeing",
                            Region = "Hoi An",
                            Title = "Private Custom Journey",
                            Type = "Combo",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Cms.Repository.Entities.SiteSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LegalName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Manifesto")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("OfficesJson")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SocialJson")
                        .HasColumnType("text");

                    b.Property<string>("Tagline")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TaxId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SiteSettings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777771"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sample site description.",
                            Email = "hello@perlunas.local",
                            IsDeleted = false,
                            LegalName = "Perlunas Travel Co., Ltd.",
                            Manifesto = "Sample manifesto.",
                            Name = "Perlunas",
                            OfficesJson = "[]",
                            Phone = "+84000000000",
                            SocialJson = "{}",
                            Tagline = "Travel with care",
                            TaxId = "0000000000",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777772"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Support channel information.",
                            Email = "support@perlunas.local",
                            IsDeleted = false,
                            LegalName = "Perlunas Travel Co., Ltd.",
                            Manifesto = "Support-focused contact settings.",
                            Name = "Perlunas Support",
                            OfficesJson = "[]",
                            Phone = "+84111111111",
                            SocialJson = "{}",
                            Tagline = "Always here to help",
                            TaxId = "0000000000",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777773"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Branch contact information.",
                            Email = "danang@perlunas.local",
                            IsDeleted = false,
                            LegalName = "Perlunas Da Nang Branch",
                            Manifesto = "Local branch settings.",
                            Name = "Perlunas Da Nang",
                            OfficesJson = "[]",
                            Phone = "+84222222222",
                            SocialJson = "{}",
                            Tagline = "Central Vietnam office",
                            TaxId = "0000000001",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Cms.Repository.Entities.DepartureSchedule", b =>
                {
                    b.HasOne("Cms.Repository.Entities.Service", "Service")
                        .WithMany("DepartureSchedules")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Cms.Repository.Entities.ImportantInfor", b =>
                {
                    b.HasOne("Cms.Repository.Entities.Service", "Service")
                        .WithMany("ImportantInfors")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Cms.Repository.Entities.PageContent", b =>
                {
                    b.HasOne("Cms.Repository.Entities.PageContent", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Cms.Repository.Entities.RoomCategory", b =>
                {
                    b.HasOne("Cms.Repository.Entities.Service", "Service")
                        .WithMany("RoomCategories")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Cms.Repository.Entities.Schedule", b =>
                {
                    b.HasOne("Cms.Repository.Entities.Service", "Service")
                        .WithMany("Schedules")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Cms.Repository.Entities.PageContent", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Cms.Repository.Entities.Service", b =>
                {
                    b.Navigation("DepartureSchedules");

                    b.Navigation("ImportantInfors");

                    b.Navigation("RoomCategories");

                    b.Navigation("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
