// <auto-generated />
using System;
using System.Collections.Generic;
using Cms.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cms.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260702175657_AddTourHighlightContent")]
    partial class AddTourHighlightContent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cms.Repository.Entities.Blog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ReadingTime")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SubTitile")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Tag")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Titile")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Blogs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888881"),
                            Author = "Perlunas Admin",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sample blog content.",
                            IsDeleted = false,
                            ReadingTime = "5 min",
                            SubTitile = "Start here",
                            Tag = "guide",
                            Titile = "Sample travel guide",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888882"),
                            Author = "Perlunas Admin",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tips for selecting a resort package.",
                            IsDeleted = false,
                            ReadingTime = "7 min",
                            SubTitile = "Family travel tips",
                            Tag = "resort",
                            Titile = "How to choose a resort",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888883"),
                            Author = "Perlunas Admin",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "How to prepare for a private custom trip.",
                            IsDeleted = false,
                            ReadingTime = "6 min",
                            SubTitile = "Flexible journeys",
                            Tag = "private-tour",
                            Titile = "Private tour planning",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Cms.Repository.Entities.DepartureSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccommodationStandards")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Price")
                        .HasColumnType("text");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("StartTime")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("DepartureSchedules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444441"),
                            AccommodationStandards = "3-star hotel",
                            Code = "DEP-001",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Price = "3500000/customer",
                            ServiceId = new Guid("11111111-1111-1111-1111-111111111111"),
                            StartTime = "2026-07-15",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444442"),
                            AccommodationStandards = "4-star resort",
                            Code = "DEP-002",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Price = "5200000/customer",
                            ServiceId = new Guid("11111111-1111-1111-1111-111111111111"),
                            StartTime = "2026-09-20",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444443"),
                            AccommodationStandards = "Boutique hotel",
                            Code = "DEP-003",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Price = "Quote on request",
                            ServiceId = new Guid("11111111-1111-1111-1111-111111111111"),
                            StartTime = "On request",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-333333333311"),
                            AccommodationStandards = "3-star hotel",
                            Code = "DEP-VN1",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Price = "4000000/customer",
                            ServiceId = new Guid("11111111-1111-1111-1111-333333333311"),
                            StartTime = "Weekly",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-333333333312"),
                            AccommodationStandards = "3-star hotel",
                            Code = "DEP-VN2",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Price = "4500000/customer",
                            ServiceId = new Guid("11111111-1111-1111-1111-333333333312"),
                            StartTime = "Weekly",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-333333333313"),
                            AccommodationStandards = "3-star hotel",
                            Code = "DEP-TH1",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Price = "3800000/customer",
                            ServiceId = new Guid("11111111-1111-1111-1111-333333333313"),
                            StartTime = "Weekly",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Cms.Repository.Entities.ImportantInfor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubTitle")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("ImportantInfors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555551"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Xe du lịch đời mới máy lạnh đưa đón theo chương trình.\nKhách sạn theo tiêu chuẩn, 2 - 3 khách/phòng.\nCác bữa ăn theo chương trình.\nVé tham quan các điểm có trong chương trình.\nHướng dẫn viên kinh nghiệm phục vụ suốt tuyến.\nBảo hiểm du lịch và nước suối trên xe.",
                            IsDeleted = false,
                            ServiceId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SubTitle = "",
                            Title = "Giá tour bao gồm",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-5555555555a1"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Chi phí cá nhân, giặt ủi, điện thoại, đồ uống ngoài chương trình.\nTiền tip cho hướng dẫn viên và tài xế.\nPhụ thu phòng đơn.\nThuế VAT và hóa đơn đỏ (nếu khách yêu cầu).",
                            IsDeleted = false,
                            ServiceId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SubTitle = "",
                            Title = "Giá tour chưa bao gồm",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-5555555555a2"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Trẻ dưới 5 tuổi: miễn phí, ngủ chung với bố mẹ; 2 người lớn kèm tối đa 1 trẻ.\nTrẻ 5 - dưới 10 tuổi: tính 50% giá tour.\nTrẻ từ 10 tuổi trở lên: tính như người lớn.",
                            IsDeleted = false,
                            ServiceId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SubTitle = "",
                            Title = "Giá trẻ em",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-5555555555a3"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Đặt cọc 50% giá tour ngay khi đăng ký để giữ chỗ.\nThanh toán phần còn lại trước ngày khởi hành tối thiểu 7 ngày.\nCung cấp đầy đủ thông tin: họ tên, năm sinh, số CMND/CCCD/hộ chiếu.",
                            IsDeleted = false,
                            ServiceId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SubTitle = "",
                            Title = "Điều kiện đăng ký và thanh toán",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-5555555555a4"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Huỷ trước khởi hành từ 15 ngày: phí 30% giá tour.\nHuỷ trước 7 - 14 ngày: phí 50% giá tour.\nHuỷ trong vòng 6 ngày hoặc không khởi hành (no-show): phí 100% giá tour.",
                            IsDeleted = false,
                            ServiceId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SubTitle = "Ngày thường",
                            Title = "Điều kiện đổi và huỷ tour",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-5555555555a5"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thiên tai, dịch bệnh, thời tiết xấu, chuyến bay delay/huỷ… hai bên cùng thương lượng giải quyết hợp lý, đảm bảo quyền lợi tối đa cho khách.\nPerlunas có quyền thay đổi lộ trình vì lý do an toàn nhưng vẫn đảm bảo tiêu chuẩn dịch vụ.",
                            IsDeleted = false,
                            ServiceId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SubTitle = "",
                            Title = "Trường hợp bất khả kháng",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555552"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Quý khách xuất trình giấy tờ tuỳ thân hợp lệ khi nhận phòng.",
                            IsDeleted = false,
                            ServiceId = new Guid("11111111-1111-1111-1111-111111111113"),
                            SubTitle = "Giấy tờ cần thiết",
                            Title = "Nhận phòng",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555553"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lịch trình cuối cùng được xác nhận trước ngày khởi hành 48 giờ.",
                            IsDeleted = false,
                            ServiceId = new Guid("11111111-1111-1111-1111-111111111113"),
                            SubTitle = "Thiết kế theo yêu cầu",
                            Title = "Lịch trình riêng",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Cms.Repository.Entities.PageContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentValue")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Kind")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Label")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PageKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("SectionKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("SoftOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("PageKey", "SectionKey", "Key");

                    b.ToTable("PageContents", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666661"),
                            ContentValue = "Discover Perlunas",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Key = "title",
                            Kind = "text",
                            Label = "Hero title",
                            PageKey = "home",
                            SectionKey = "hero",
                            SoftOrder = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666662"),
                            ContentValue = "We craft thoughtful travel experiences.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Key = "description",
                            Kind = "textarea",
                            Label = "About intro",
                            PageKey = "about",
                            SectionKey = "intro",
                            SoftOrder = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666663"),
                            ContentValue = "Choose a journey that fits your style.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Key = "subtitle",
                            Kind = "text",
                            Label = "Service banner subtitle",
                            PageKey = "services",
                            SectionKey = "banner",
                            SoftOrder = 2,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666671"),
                            ContentValue = "Explore breathtaking destinations with us",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Key = "subtitle",
                            Kind = "text",
                            Label = "Hero subtitle",
                            PageKey = "home",
                            ParentId = new Guid("66666666-6666-6666-6666-666666666661"),
                            SectionKey = "hero",
                            SoftOrder = 2,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666672"),
                            ContentValue = "Book Now",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Key = "cta",
                            Kind = "text",
                            Label = "Hero CTA button",
                            PageKey = "home",
                            ParentId = new Guid("66666666-6666-6666-6666-666666666661"),
                            SectionKey = "hero",
                            SoftOrder = 3,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Cms.Repository.Entities.RoomCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Acreage")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Album")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Feature")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("NumberOfBed")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("NumberOfCustomer")
                        .HasColumnType("integer");

                    b.Property<string>("OriginalPrice")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Price")
                        .HasColumnType("text");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Titile")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Unit")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("RoomCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333331"),
                            Acreage = "35m2",
                            Album = "[]",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sample deluxe room.",
                            Feature = "[\"Balcony\",\"breakfast\",\"sea view\"]",
                            IsDeleted = false,
                            NumberOfBed = "1",
                            NumberOfCustomer = 2,
                            OriginalPrice = "1500000",
                            Price = "1200000",
                            ServiceId = new Guid("11111111-1111-1111-1111-111111111112"),
                            Titile = "Deluxe Room",
                            Unit = "đêm",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333332"),
                            Acreage = "80m2",
                            Album = "[]",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Private family villa near the beach.",
                            Feature = "[\"Private pool\",\"kitchen\",\"breakfast\"]",
                            IsDeleted = false,
                            NumberOfBed = "2",
                            NumberOfCustomer = 4,
                            OriginalPrice = "4000000",
                            Price = "3500000",
                            ServiceId = new Guid("11111111-1111-1111-1111-111111111112"),
                            Titile = "Family Villa",
                            Unit = "đêm",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Acreage = "45m2",
                            Album = "[]",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Suite for private journey guests.",
                            Feature = "[\"Old town view\",\"breakfast\"]",
                            IsDeleted = false,
                            NumberOfBed = "1",
                            NumberOfCustomer = 2,
                            OriginalPrice = "2200000",
                            ServiceId = new Guid("11111111-1111-1111-1111-111111111113"),
                            Titile = "Heritage Suite",
                            Unit = "đêm",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-111111111111"),
                            Acreage = "25m2",
                            Album = "[]",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Comfortable standard room for tour guests.",
                            Feature = "[\"Wifi\",\"TV\"]",
                            IsDeleted = false,
                            NumberOfBed = "2",
                            NumberOfCustomer = 2,
                            OriginalPrice = "1000000",
                            Price = "800000",
                            ServiceId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Titile = "Standard Tour Room",
                            Unit = "night",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-111111111112"),
                            Acreage = "28m2",
                            Album = "[]",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cozy superior room with city views.",
                            Feature = "[\"Wifi\",\"Mini-bar\"]",
                            IsDeleted = false,
                            NumberOfBed = "1",
                            NumberOfCustomer = 2,
                            OriginalPrice = "1200000",
                            Price = "1000000",
                            ServiceId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Titile = "Superior Tour Room",
                            Unit = "night",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-111111111113"),
                            Acreage = "32m2",
                            Album = "[]",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Deluxe room offering premium comfort.",
                            Feature = "[\"Wifi\",\"Balcony\",\"AC\"]",
                            IsDeleted = false,
                            NumberOfBed = "1 Large",
                            NumberOfCustomer = 2,
                            OriginalPrice = "1600000",
                            Price = "1300000",
                            ServiceId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Titile = "Deluxe Tour Room",
                            Unit = "night",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-111111111114"),
                            Acreage = "45m2",
                            Album = "[]",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Executive suite with a separate lounge area.",
                            Feature = "[\"Lounge access\",\"Bathtub\"]",
                            IsDeleted = false,
                            NumberOfBed = "1 King + 1 Single",
                            NumberOfCustomer = 3,
                            OriginalPrice = "2500000",
                            Price = "2000000",
                            ServiceId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Titile = "Executive Tour Suite",
                            Unit = "night",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-111111111115"),
                            Acreage = "50m2",
                            Album = "[]",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Perfect suite designed for family travelers.",
                            Feature = "[\"Kid friendly\",\"Kitchenette\"]",
                            IsDeleted = false,
                            NumberOfBed = "2 Large",
                            NumberOfCustomer = 4,
                            OriginalPrice = "3000000",
                            Price = "2500000",
                            ServiceId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Titile = "Family Tour Suite",
                            Unit = "night",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-111111111116"),
                            Acreage = "40m2",
                            Album = "[]",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Indulge in our premium tour suite experience.",
                            Feature = "[\"Jacuzzi\",\"Welcome drink\"]",
                            IsDeleted = false,
                            NumberOfBed = "1 King",
                            NumberOfCustomer = 2,
                            OriginalPrice = "2800000",
                            Price = "2200000",
                            ServiceId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Titile = "Premium Tour Suite",
                            Unit = "night",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-111111111117"),
                            Acreage = "38m2",
                            Album = "[]",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Direct pool access from your patio.",
                            Feature = "[\"Pool access\",\"Patio\"]",
                            IsDeleted = false,
                            NumberOfBed = "1 King",
                            NumberOfCustomer = 2,
                            OriginalPrice = "2200000",
                            Price = "1800000",
                            ServiceId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Titile = "Tour Cabana Room",
                            Unit = "night",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-111111111118"),
                            Acreage = "30m2",
                            Album = "[]",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Room featuring panoramic floor-to-ceiling windows.",
                            Feature = "[\"View\",\"Coffee maker\"]",
                            IsDeleted = false,
                            NumberOfBed = "1 Queen",
                            NumberOfCustomer = 2,
                            OriginalPrice = "1800000",
                            Price = "1500000",
                            ServiceId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Titile = "Panoramic View Room",
                            Unit = "night",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-111111111119"),
                            Acreage = "42m2",
                            Album = "[]",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Romantic suite styled for honeymooners.",
                            Feature = "[\"Flowers\",\"Champagne\"]",
                            IsDeleted = false,
                            NumberOfBed = "1 King",
                            NumberOfCustomer = 2,
                            OriginalPrice = "3000000",
                            Price = "2400000",
                            ServiceId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Titile = "Honeymoon Tour Suite",
                            Unit = "night",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-111111111120"),
                            Acreage = "120m2",
                            Album = "[]",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The ultimate luxury stay with top amenities.",
                            Feature = "[\"Butler service\",\"Kitchen\"]",
                            IsDeleted = false,
                            NumberOfBed = "2 King",
                            NumberOfCustomer = 4,
                            OriginalPrice = "6500000",
                            Price = "5000000",
                            ServiceId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Titile = "Presidential Tour Suite",
                            Unit = "night",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-222222222211"),
                            Acreage = "30m2",
                            Album = "[]",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Eco-friendly wood cabin room.",
                            Feature = "[\"Mountain view\",\"organic tea\"]",
                            IsDeleted = false,
                            NumberOfBed = "1 Queen",
                            NumberOfCustomer = 2,
                            OriginalPrice = "1100000",
                            Price = "950000",
                            ServiceId = new Guid("11111111-1111-1111-1111-222222222211"),
                            Titile = "Eco Lodge Room",
                            Unit = "night",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-222222222212"),
                            Acreage = "45m2",
                            Album = "[]",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Luxurious royal room with classic decor.",
                            Feature = "[\"City view\",\"jacuzzi\"]",
                            IsDeleted = false,
                            NumberOfBed = "1 King",
                            NumberOfCustomer = 2,
                            OriginalPrice = "2600000",
                            Price = "2100000",
                            ServiceId = new Guid("11111111-1111-1111-1111-222222222212"),
                            Titile = "Royal Suite",
                            Unit = "night",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-222222222213"),
                            Acreage = "35m2",
                            Album = "[]",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Charming room with historical accents.",
                            Feature = "[\"Garden view\",\"espresso machine\"]",
                            IsDeleted = false,
                            NumberOfBed = "1 Double",
                            NumberOfCustomer = 2,
                            OriginalPrice = "1700000",
                            Price = "1400000",
                            ServiceId = new Guid("11111111-1111-1111-1111-222222222213"),
                            Titile = "Heritage Room",
                            Unit = "night",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-222222222214"),
                            Acreage = "40m2",
                            Album = "[]",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Direct beach view from your room balcony.",
                            Feature = "[\"Beachfront\",\"Sunset view\"]",
                            IsDeleted = false,
                            NumberOfBed = "1 King",
                            NumberOfCustomer = 2,
                            OriginalPrice = "3300000",
                            Price = "2800000",
                            ServiceId = new Guid("11111111-1111-1111-1111-222222222214"),
                            Titile = "Sunset Beach Room",
                            Unit = "night",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Cms.Repository.Entities.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Day")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sumary")
                        .HasColumnType("text");

                    b.Property<string>("Titile")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("Schedules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222221"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Day = "Day 1",
                            Description = "Airport pickup and welcome dinner.",
                            IsDeleted = false,
                            ServiceId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Sumary = "Arrive and settle in.",
                            Titile = "Arrival",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Day = "Day 2",
                            Description = "Guided tour and local activities.",
                            IsDeleted = false,
                            ServiceId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Sumary = "Explore the destination.",
                            Titile = "Experience",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222223"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Day = "Day 1",
                            Description = "Welcome drink, room check-in, free beach time.",
                            IsDeleted = false,
                            ServiceId = new Guid("11111111-1111-1111-1111-111111111112"),
                            Sumary = "Check in and relax.",
                            Titile = "Resort check-in",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222224"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Day = "Day 1",
                            Description = "Custom stops based on customer preference.",
                            IsDeleted = false,
                            ServiceId = new Guid("11111111-1111-1111-1111-111111111113"),
                            Sumary = "Private tour with local guide.",
                            Titile = "Private discovery",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Cms.Repository.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Album")
                        .HasColumnType("text");

                    b.Property<bool>("BestSeller")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Classify")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("Day")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Destination")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<List<string>>("Destinations")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<List<string>>("Facilities")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Feature")
                        .HasColumnType("text");

                    b.Property<string>("Form")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<List<string>>("Highlight")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("HighlightContent")
                        .HasColumnType("text");

                    b.Property<string>("Infor")
                        .HasColumnType("text");

                    b.Property<string>("Instruct")
                        .HasColumnType("text");

                    b.Property<string>("Introducetion")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("Night")
                        .HasColumnType("integer");

                    b.Property<string>("PurposeOfTrip")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Region")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Type");

                    b.ToTable("Services", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Album = "[]",
                            BestSeller = true,
                            Code = "PLN-001",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Day = 3,
                            Description = "Sample service description.",
                            Destinations = new List<string> { "Da Nang Beach" },
                            Facilities = new List<string>(),
                            Feature = "Sample features.",
                            Highlight = new List<string> { "Sample service highlights." },
                            HighlightContent = "<h3>Điểm nhấn hành trình</h3><ul><li>Ngắm hoàng hôn trên biển Đà Nẵng</li><li>Dạo phố cổ Hội An lung linh đèn lồng</li><li>Thưởng thức tinh hoa ẩm thực miền Trung</li></ul><h3>Du lịch Bền vững (ESG)</h3><p>Tôn vinh cảnh quan thiên nhiên, kết nối cộng đồng địa phương qua các làng nghề và không gian bản địa.</p><h3>Trải nghiệm Bản địa (LEI)</h3><p>Khám phá văn hóa – lịch sử tiêu biểu và những trải nghiệm chỉ có tại điểm đến.</p>",
                            Infor = "Sample service information.",
                            Instruct = "Sample instructions.",
                            Introducetion = "Sample introduction for the main service.",
                            IsDeleted = false,
                            IsPublic = true,
                            Label = "Featured",
                            Night = 2,
                            Region = "Vietnam",
                            Slug = "perlunas-signature-tour",
                            Title = "Perlunas Signature Tour",
                            Type = "Tour",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            Album = "[]",
                            BestSeller = false,
                            Code = "PLN-002",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Day = 4,
                            Description = "Beachfront resort package.",
                            Destination = "Da Nang Beach",
                            Destinations = new List<string>(),
                            Facilities = new List<string> { "Wifi miễn phí", "Hồ bơi", "Bữa sáng", "Bãi đỗ xe", "Nhà hàng", "Lễ tân 24h", "Điều hòa", "Phòng gym" },
                            Form = "Full-board",
                            Highlight = new List<string> { "Private beach", "spa", "local dining" },
                            Infor = "Includes room and breakfast.",
                            IsDeleted = false,
                            IsPublic = true,
                            Night = 3,
                            PurposeOfTrip = "Nghỉ dưỡng",
                            Region = "Da Nang",
                            Slug = "beach-resort-package",
                            Title = "Beach Resort Package",
                            Type = "Hotel",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111113"),
                            Album = "[]",
                            BestSeller = false,
                            Classify = "Akoya",
                            Code = "PLN-003",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Day = 2,
                            Description = "Private travel experience.",
                            Destination = "Hoi An Ancient Town",
                            Destinations = new List<string>(),
                            Facilities = new List<string>(),
                            Feature = "Private guide, custom route",
                            Form = "Half-board",
                            Highlight = new List<string> { "Flexible route", "private guide" },
                            Infor = "Dedicated guide and vehicle.",
                            Instruct = "Confirm itinerary before departure.",
                            Introducetion = "Custom private trip with flexible schedule.",
                            IsDeleted = false,
                            IsPublic = true,
                            Label = "Private",
                            Night = 1,
                            PurposeOfTrip = "Tham quan",
                            Region = "Hoi An",
                            Slug = "private-custom-journey",
                            Title = "Private Custom Journey",
                            Type = "Combo",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-222222222211"),
                            Album = "[]",
                            BestSeller = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Destination = "Sapa Valley",
                            Destinations = new List<string>(),
                            Facilities = new List<string> { "Wifi miễn phí", "Hồ bơi", "Bữa sáng", "Bãi đỗ xe", "Nhà hàng", "Lễ tân 24h", "Điều hòa", "Phòng gym" },
                            Feature = "Mountain view, organic restaurant",
                            Form = "Bed and breakfast",
                            Highlight = new List<string>(),
                            Instruct = "Eco guidelines apply.",
                            Introducetion = "Scenic lodge in the heart of nature.",
                            IsDeleted = false,
                            IsPublic = true,
                            PurposeOfTrip = "Nghỉ dưỡng",
                            Region = "Vietnam",
                            Slug = "vietnam-eco-lodge",
                            Title = "Vietnam Eco Lodge",
                            Type = "Hotel",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-222222222212"),
                            Album = "[]",
                            BestSeller = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Destination = "Hanoi Old Quarter",
                            Destinations = new List<string>(),
                            Facilities = new List<string> { "Wifi miễn phí", "Hồ bơi", "Bữa sáng", "Bãi đỗ xe", "Nhà hàng", "Lễ tân 24h", "Điều hòa", "Phòng gym" },
                            Feature = "City view, spa, fitness center",
                            Form = "Room only",
                            Highlight = new List<string>(),
                            Instruct = "Check-in after 14:00.",
                            Introducetion = "Luxury hotel in the historical quarter.",
                            IsDeleted = false,
                            IsPublic = true,
                            PurposeOfTrip = "Tham quan",
                            Region = "Vietnam",
                            Slug = "hanoi-royal-palace-hotel",
                            Title = "Hanoi Royal Palace Hotel",
                            Type = "Hotel",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-222222222213"),
                            Album = "[]",
                            BestSeller = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Destination = "Ho Chi Minh City",
                            Destinations = new List<string>(),
                            Facilities = new List<string> { "Wifi miễn phí", "Hồ bơi", "Bữa sáng", "Bãi đỗ xe", "Nhà hàng", "Lễ tân 24h", "Điều hòa", "Phòng gym" },
                            Feature = "Rooftop bar, pool",
                            Form = "Room only",
                            Highlight = new List<string>(),
                            Instruct = "Strictly non-smoking.",
                            Introducetion = "Elegant boutique hotel reflecting local heritage.",
                            IsDeleted = false,
                            IsPublic = true,
                            PurposeOfTrip = "Tham quan",
                            Region = "Vietnam",
                            Slug = "saigon-heritage-hotel",
                            Title = "Saigon Heritage Hotel",
                            Type = "Hotel",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-222222222214"),
                            Album = "[]",
                            BestSeller = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Destination = "Phu Quoc Island",
                            Destinations = new List<string>(),
                            Facilities = new List<string> { "Wifi miễn phí", "Hồ bơi", "Bữa sáng", "Bãi đỗ xe", "Nhà hàng", "Lễ tân 24h", "Điều hòa", "Phòng gym" },
                            Feature = "Private beach, infinity pool",
                            Form = "Full-board",
                            Highlight = new List<string>(),
                            Instruct = "No pets allowed.",
                            Introducetion = "Seaside resort with stunning sunset views.",
                            IsDeleted = false,
                            IsPublic = true,
                            PurposeOfTrip = "Nghỉ dưỡng",
                            Region = "Vietnam",
                            Slug = "phu-quoc-sunset-resort",
                            Title = "Phu Quoc Sunset Resort",
                            Type = "Hotel",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-333333333311"),
                            Album = "[]",
                            BestSeller = false,
                            Code = "TOUR-VN1",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Day = 5,
                            Description = "Explore rich heritage.",
                            Destinations = new List<string>(),
                            Facilities = new List<string>(),
                            Highlight = new List<string> { "Historic sites." },
                            Infor = "All inclusive tour.",
                            Introducetion = "Sample tour in Vietnam.",
                            IsDeleted = false,
                            IsPublic = true,
                            Night = 4,
                            Region = "Vietnam",
                            Slug = "vietnam-heritage-discovery-tour",
                            Title = "Vietnam Heritage Discovery Tour",
                            Type = "Tour",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-333333333312"),
                            Album = "[]",
                            BestSeller = false,
                            Code = "TOUR-VN2",
                            CreatedAt = new DateTime(2026, 1, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                            Day = 6,
                            Description = "Explore natural highlights.",
                            Destinations = new List<string>(),
                            Facilities = new List<string>(),
                            Highlight = new List<string> { "Spectacular bays." },
                            Infor = "All inclusive tour.",
                            Introducetion = "Sample tour in northern Vietnam.",
                            IsDeleted = false,
                            IsPublic = true,
                            Night = 5,
                            Region = "Vietnam",
                            Slug = "vietnam-northern-highlights",
                            Title = "Vietnam Northern Highlights",
                            Type = "Tour",
                            UpdatedAt = new DateTime(2026, 1, 1, 1, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-333333333313"),
                            Album = "[]",
                            BestSeller = false,
                            Code = "TOUR-TH1",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Day = 4,
                            Description = "Explore Thai islands.",
                            Destinations = new List<string>(),
                            Facilities = new List<string>(),
                            Highlight = new List<string> { "Bangkok and Phuket." },
                            Infor = "Flight not included.",
                            Introducetion = "Sample tour in Thailand.",
                            IsDeleted = false,
                            IsPublic = true,
                            Night = 3,
                            Region = "Thailand",
                            Slug = "thailand-paradise-getaway",
                            Title = "Thailand Paradise Getaway",
                            Type = "Tour",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Cms.Repository.Entities.SiteSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LegalName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Manifesto")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("OfficesJson")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SocialJson")
                        .HasColumnType("text");

                    b.Property<string>("Tagline")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TaxId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SiteSettings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777771"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sample site description.",
                            Email = "hello@perlunas.local",
                            IsDeleted = false,
                            LegalName = "Perlunas Travel Co., Ltd.",
                            Manifesto = "Sample manifesto.",
                            Name = "Perlunas",
                            OfficesJson = "[]",
                            Phone = "+84000000000",
                            SocialJson = "{}",
                            Tagline = "Travel with care",
                            TaxId = "0000000000",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777772"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Support channel information.",
                            Email = "support@perlunas.local",
                            IsDeleted = false,
                            LegalName = "Perlunas Travel Co., Ltd.",
                            Manifesto = "Support-focused contact settings.",
                            Name = "Perlunas Support",
                            OfficesJson = "[]",
                            Phone = "+84111111111",
                            SocialJson = "{}",
                            Tagline = "Always here to help",
                            TaxId = "0000000000",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777773"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Branch contact information.",
                            Email = "danang@perlunas.local",
                            IsDeleted = false,
                            LegalName = "Perlunas Da Nang Branch",
                            Manifesto = "Local branch settings.",
                            Name = "Perlunas Da Nang",
                            OfficesJson = "[]",
                            Phone = "+84222222222",
                            SocialJson = "{}",
                            Tagline = "Central Vietnam office",
                            TaxId = "0000000001",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Cms.Repository.Entities.Taxonomy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Slug")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Group");

                    b.HasIndex("Group", "Name")
                        .IsUnique();

                    b.ToTable("Taxonomies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "city",
                            IsDeleted = false,
                            Name = "Hà Nội",
                            Slug = "ha-noi",
                            SortOrder = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "city",
                            IsDeleted = false,
                            Name = "TP. Hồ Chí Minh",
                            Slug = "ho-chi-minh",
                            SortOrder = 2,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "city",
                            IsDeleted = false,
                            Name = "Hạ Long",
                            Slug = "ha-long",
                            SortOrder = 3,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "city",
                            IsDeleted = false,
                            Name = "Đà Lạt",
                            Slug = "da-lat",
                            SortOrder = 4,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000005"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "city",
                            IsDeleted = false,
                            Name = "Đà Nẵng",
                            Slug = "da-nang",
                            SortOrder = 5,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000006"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "city",
                            IsDeleted = false,
                            Name = "Phú Quốc",
                            Slug = "phu-quoc",
                            SortOrder = 6,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000007"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "city",
                            IsDeleted = false,
                            Name = "Nha Trang",
                            Slug = "nha-trang",
                            SortOrder = 7,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000008"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "city",
                            IsDeleted = false,
                            Name = "Huế",
                            Slug = "hue",
                            SortOrder = 8,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000009"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "city",
                            IsDeleted = false,
                            Name = "Sa Pa",
                            Slug = "sa-pa",
                            SortOrder = 9,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000010"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "region",
                            IsDeleted = false,
                            Name = "Miền Bắc",
                            SortOrder = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000011"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "region",
                            IsDeleted = false,
                            Name = "Miền Trung",
                            SortOrder = 2,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000012"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "region",
                            IsDeleted = false,
                            Name = "Miền Nam",
                            SortOrder = 3,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000013"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "region",
                            IsDeleted = false,
                            Name = "Tây Nguyên",
                            SortOrder = 4,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000014"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "stay-type",
                            IsDeleted = false,
                            Name = "Hotel",
                            SortOrder = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000015"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "stay-type",
                            IsDeleted = false,
                            Name = "Resort",
                            SortOrder = 2,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000016"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "stay-type",
                            IsDeleted = false,
                            Name = "Retreat",
                            SortOrder = 3,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000017"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "stay-type",
                            IsDeleted = false,
                            Name = "Wellness",
                            SortOrder = 4,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000018"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "stay-type",
                            IsDeleted = false,
                            Name = "Boutique Hotel",
                            SortOrder = 5,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000019"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "tier",
                            IsDeleted = false,
                            Name = "Akoya",
                            SortOrder = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000020"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "tier",
                            IsDeleted = false,
                            Name = "Tahiti",
                            SortOrder = 2,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000021"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "tier",
                            IsDeleted = false,
                            Name = "South Sea",
                            SortOrder = 3,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000022"),
                            Color = "#3F9D6B",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "purpose",
                            IsDeleted = false,
                            Name = "Nghỉ dưỡng",
                            SortOrder = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000023"),
                            Color = "#D6A12B",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "purpose",
                            IsDeleted = false,
                            Name = "Tham quan",
                            SortOrder = 2,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000024"),
                            Color = "#C24A33",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "purpose",
                            IsDeleted = false,
                            Name = "Công tác",
                            SortOrder = 3,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000025"),
                            Color = "#8159A6",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "purpose",
                            IsDeleted = false,
                            Name = "Thăm thân",
                            SortOrder = 4,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Cms.Repository.Entities.DepartureSchedule", b =>
                {
                    b.HasOne("Cms.Repository.Entities.Service", "Service")
                        .WithMany("DepartureSchedules")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Cms.Repository.Entities.ImportantInfor", b =>
                {
                    b.HasOne("Cms.Repository.Entities.Service", "Service")
                        .WithMany("ImportantInfors")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Cms.Repository.Entities.PageContent", b =>
                {
                    b.HasOne("Cms.Repository.Entities.PageContent", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Cms.Repository.Entities.RoomCategory", b =>
                {
                    b.HasOne("Cms.Repository.Entities.Service", "Service")
                        .WithMany("RoomCategories")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Cms.Repository.Entities.Schedule", b =>
                {
                    b.HasOne("Cms.Repository.Entities.Service", "Service")
                        .WithMany("Schedules")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Cms.Repository.Entities.PageContent", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Cms.Repository.Entities.Service", b =>
                {
                    b.Navigation("DepartureSchedules");

                    b.Navigation("ImportantInfors");

                    b.Navigation("RoomCategories");

                    b.Navigation("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
